import { useState } from 'react'
import './App.css'
import exampleCat from './assets/cat.png'

// FIX: Define what your API response looks like
interface StoryResult {
  message: string;
  story_text: string;
  image_url: string;
}

function App() {
  const [prompt, setPrompt] = useState<string>('')
  const [result, setResult] = useState<StoryResult | null>(null)
  const [loading, setLoading] = useState<boolean>(false)
  const [error, setError] = useState<string | null>(null)

  const API_URL = import.meta.env.VITE_API_URL;

  const generateStory = async () => {
    if (!prompt) return;
    
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const response = await fetch(API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: prompt })
      });

      if (!response.ok) throw new Error('Generation failed');

      // FIX: Tell TypeScript this data matches our StoryResult interface
      const data: StoryResult = await response.json();
      setResult(data);
    } catch (err: unknown) {
      // FIX: Safely handle the error type
      if (err instanceof Error) {
        setError(err.message);
      } else {
        setError("An unexpected error occurred");
      }
    } finally {
      setLoading(false);
    }
  };

  const wordCount = (text: string | undefined) => {
    if (!text) return 0;
    return text.trim().split(/\s+/).length;
  }

  return (
    <div className="container">
      <header className="hero">
        <h1>Bedrock Storyteller</h1>
        <p className="subtitle">Short, vivid stories and evocative images, tailored from your ideas.</p>
      </header>

      <section className="example-section">
        <div className="example-card">
          <div className="example-image">
            <img src={exampleCat} alt="Cyberpunk cat in neon city" />
          </div>
          <div className="example-body">
            <h4>Example: Cyberpunk Cat</h4>
            <p className="example-text">A sleek cyberpunk cat prowls a neon-lit city at night, reflecting chrome and neon in its eyes, weaving through rain-slick alleys and luminous signs.</p>
            <div className="example-actions">
              <button className="chip" type="button" onClick={() => setPrompt('A cyberpunk cat prowling a neon city at night')}>Use Example</button>
            </div>
          </div>
        </div>
      </section>

      <div className="input-group">
        <textarea 
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Enter a topic (e.g., A cyberpunk cat in a neon city...)"
          rows={3}
          aria-label="Story prompt"
        />
        <div className="prompts">
          {['A curious librarian discovers a hidden map','A rainy city where streetlights whisper','A child befriends a lost star'].map(p => (
            <button key={p} className="chip" onClick={() => setPrompt(p)} type="button">{p}</button>
          ))}
        </div>
        <div className="actions">
          <button className="primary" onClick={generateStory} disabled={loading}>
            {loading ? 'Generating...' : 'Create Story'}
          </button>
        </div>
      </div>

      {loading && <div className="loader">Generating story<span className="dot">.</span><span className="dot">.</span><span className="dot">.</span></div>}
      
      {error && <div className="error">{error}</div>}

      {result && (
        <div className="result-card">
          <div className="image-container">
            <img src={result.image_url} alt="Generated scene" />
          </div>
          <div className="story-content">
            <div className="story-header">
              <h3 className="story-title">Generated Story</h3>
              <div className="meta">{wordCount(result.story_text)} words</div>
            </div>
            <p>{result.story_text}</p>
            <footer className="card-footer">
              <small className="attribution">Images & text generated by the pipeline • <strong>Share responsibly</strong></small>
            </footer>
          </div>
        </div>
      )}

      <footer className="page-footer">
        <small>Made with care. Keep prompts human and imaginative.</small>
      </footer>
      <a className="github-link" href="https://github.com/prabeen6260/bedrock-story-teller" target="_blank" rel="noopener noreferrer" aria-label="GitHub">
        <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" role="img">
          <title>GitHub</title>
          <path d="M12 0.297C5.37 0.297 0 5.667 0 12.297c0 5.295 3.438 9.785 8.207 11.387.6.11.82-.26.82-.577 0-.285-.01-1.04-.016-2.04-3.338.726-4.042-1.61-4.042-1.61-.546-1.387-1.333-1.757-1.333-1.757-1.09-.745.083-.73.083-.73 1.205.085 1.84 1.237 1.84 1.237 1.07 1.835 2.807 1.305 3.492.998.108-.775.418-1.305.762-1.605-2.665-.303-5.467-1.332-5.467-5.93 0-1.31.467-2.38 1.235-3.22-.124-.303-.536-1.523.117-3.176 0 0 1.008-.322 3.3 1.23.957-.266 1.98-.399 3-.405 1.02.006 2.043.139 3 .405 2.29-1.553 3.297-1.23 3.297-1.23.654 1.653.242 2.873.118 3.176.77.84 1.233 1.91 1.233 3.22 0 4.61-2.807 5.625-5.48 5.92.43.372.815 1.102.815 2.222 0 1.606-.014 2.9-.014 3.293 0 .32.216.694.825.576C20.565 22.08 24 17.592 24 12.297 24 5.667 18.627.297 12 .297z" />
        </svg>
      </a>
    </div>
  )
}

export default App